server:
  port: 8082

spring:
  application:
    name: client-backend

logging:
  level:
    com.scs: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

services:
  server-service:
    base-url: http://server-service:8081
  ttp-service:
    base-url: http://ttp-service:8080

